function [trainedClassifier, validationAccuracy] = trainKNN(trainingData)
inputTable = trainingData;
inputTable = [inputTable(:,setdiff(inputTable.Properties.VariableNames,...
    {'Features'})), array2table(table2array(inputTable(:,{'Features'})),...
    'VariableNames', {'Features_1', 'Features_2', 'Features_3',...
    'Features_4', 'Features_5', 'Features_6', 'Features_7', 'Features_8',...
    'Features_9', 'Features_10', 'Features_11', 'Features_12'})];
predictorNames = {'Features_1', 'Features_2', 'Features_3', 'Features_4',...
    'Features_5', 'Features_6', 'Features_7', 'Features_8', 'Features_9',...
    'Features_10', 'Features_11', 'Features_12'};
predictors = inputTable(:, predictorNames);
response = inputTable.Label;
isCategoricalPredictor = [false, false, false, false, false, false, false,...
    false, false, false, false, false];
classificationKNN = fitcknn(...
    predictors, ...
    response, ...
    'Distance', 'Cityblock', ...
    'Exponent', [], ...
    'NumNeighbors', 8, ...
    'DistanceWeight', 'Equal', ...
    'Standardize', true, ...
    'ClassNames', categorical({'Mano Abierta'; 'Mano Relajada';...
    'Muñeca Extendida'; 'Muñeca Flexionada'; 'Puño Cerrado'}));
splitMatricesInTableFcn = @(t) [t(:,setdiff(t.Properties.VariableNames,...
    {'Features'})), array2table(table2array(t(:,{'Features'})),...
    'VariableNames', {'Features_1', 'Features_2', 'Features_3',...
    'Features_4', 'Features_5', 'Features_6', 'Features_7', 'Features_8',...
    'Features_9', 'Features_10', 'Features_11', 'Features_12'})];
extractPredictorsFromTableFcn = @(t) t(:, predictorNames);
predictorExtractionFcn = @(x) extractPredictorsFromTableFcn(splitMatricesInTableFcn(x));
knnPredictFcn = @(x) predict(classificationKNN, x);
trainedClassifier.predictFcn = @(x) knnPredictFcn(predictorExtractionFcn(x));
trainedClassifier.RequiredVariables = {'Features'};
trainedClassifier.ClassificationKNN = classificationKNN;
inputTable = trainingData;
inputTable = [inputTable(:,setdiff(inputTable.Properties.VariableNames,...
    {'Features'})), array2table(table2array(inputTable(:,{'Features'})),...
    'VariableNames', {'Features_1', 'Features_2', 'Features_3', 'Features_4',...
    'Features_5', 'Features_6', 'Features_7', 'Features_8', 'Features_9',...
    'Features_10', 'Features_11', 'Features_12'})];
predictorNames = {'Features_1', 'Features_2', 'Features_3', 'Features_4',...
    'Features_5', 'Features_6', 'Features_7', 'Features_8', 'Features_9',...
    'Features_10', 'Features_11', 'Features_12'};
predictors = inputTable(:, predictorNames);
response = inputTable.Label;
isCategoricalPredictor = [false, false, false, false, false, false, false,...
    false, false, false, false, false];
partitionedModel = crossval(trainedClassifier.ClassificationKNN, 'KFold', 5);
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
